### PR TITLE
Logo for bjtu-travel-agency

### PR DESCRIPTION
**Pull request by familqasimov**
I belive you like it. I wish good luck everyone everywhere...

Best regards
Famil Qasimov

### CODE REVIEW

**Comment by victorpugin** [comment]
Could you update assets to remove the project name under it ? The actual version is good for README but not to render in app

**Comment by familqasimov** [comment]
Ok. I'll send you in today.

29 apr 2018, Baz 12:06 tarixində Victor Pugin <notifications@github.com>
yazdı:

**Comment by familqasimov** [comment]
Hi sir. I deleted all old files and added a logo again.

Best regard
Famil Qasimov

**Comment by victorpugin** [comment]
Hi sir. Thank you for the changes. I like your logo 👍 

Best regard,
Victor Pugin

**Pull request merged**
